syntax on

set wildmenu
set lazyredraw

set hlsearch
set showmatch
set mat=2
set noerrorbells
set novisualbell


set nowrap

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

set autoindent
set number
set relativenumber
set title

let g:netrw_altv=1
let g:netrw_liststyle=3
